name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release && tar zcf rsecho-amd64.tar.gz target/debug/rsecho
      - name: upload linux artifact
        uses: softprops/action-gh-release@v1
        with:
          files: rsecho-amd64.tar.gz
